### ISSUE TITLE
Persist Folders Setting

### ISSUE THREAD

**Issue by francescosalvi** [meboev/NppOpenFileInFolders#1]
Hello there
first of all thanks for the plugin, it really helps being productive in Notepad++.
I have an issue though with the "Folders" setting: whenever Notepad++ is restarted, the value is always re-set to the initial ''C\dev\react-ui-toolkit".
As a quick and dirty solution I patched the .dll (didn't compile sources myself) to point to my project root.

**Comment by meboev** [comment]
Hi there,
Sorry for the late answer, I was very busy those days :)
You are completely right! I have not pushed the latest changes I have made :) Silly.
I corrected this with a new version - 1.02, the latest one in master now.

Cheers! And have fun! :)
